export enum UserRoles {
  USER = 'ROLE_USER',
  ADMIN = 'ROLE_ADMIN',
  EDITOR_ACTORS = 'ROLE_EDITOR_ACTORS',
  EDITOR_PROJECTS = 'ROLE_EDITOR_PROJECTS',
  EDITOR_RESSOURCES = 'ROLE_EDITOR_RESSOURCES',
  EDITOR_DATA = 'ROLE_EDITOR_DATA'
}
