export enum AdministrationPanels {
  MEMBERS = 'MEMBERS',
  CONTENT = 'CONTENT',
  CONTENT_ACTORS = 'CONTENT_ACTORS',
  CONTENT_PROJECTS = 'CONTENT_PROJECTS',
  CONTENT_RESOURCES = 'CONTENT_RESOURCES',
  COMMENTS = 'COMMENTS'
}
